# Generated by Django 5.2.7 on 2025-10-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=64, unique=True)),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField(default=False)),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
